export default [
  {
    _id: "Q101",
    course: "RS101",
    title: "Rocket Propulsion Fundamentals",
    description: "Test your knowledge of basic rocket propulsion concepts.",
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 20,
    timeLimitEnabled: true,
    multipleAttempts: true,
    howManyAttempts: 3,
    showCorrectAnswers: "immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2025-06-15",
    availableDate: "2025-05-01",
    untilDate: "2025-06-20",
    published: true,
    questions: [
      {
        _id: "Q101-1",
        type: "MULTIPLE_CHOICE",
        title: "Newton's Third Law",
        question: "Which of Newton's laws is the primary principle behind rocket propulsion?",
        points: 10,
        choices: [
          { _id: "Q101-1-A", text: "First Law – Law of Inertia" },
          { _id: "Q101-1-B", text: "Second Law – F = ma" },
          { _id: "Q101-1-C", text: "Third Law – Action and Reaction" },
          { _id: "Q101-1-D", text: "Law of Gravitation" },
        ],
        correctAnswer: "Q101-1-C",
        possibleAnswers: [],
      },
      {
        _id: "Q101-2",
        type: "TRUE_FALSE",
        title: "Vacuum Performance",
        question: "Rockets perform better in a vacuum than in the atmosphere.",
        points: 5,
        choices: [],
        correctAnswer: "true",
        possibleAnswers: [],
      },
      {
        _id: "Q101-3",
        type: "FILL_IN_BLANK",
        title: "Specific Impulse Unit",
        question: "The unit used to measure the efficiency of rocket propellant is called _______.",
        points: 10,
        choices: [],
        correctAnswer: "",
        possibleAnswers: ["specific impulse", "Isp", "isp"],
      },
      {
        _id: "Q101-4",
        type: "MULTIPLE_CHOICE",
        title: "Propellant Types",
        question: "Which type of propellant is used in the Space Shuttle Main Engines?",
        points: 10,
        choices: [
          { _id: "Q101-4-A", text: "Solid propellant" },
          { _id: "Q101-4-B", text: "Liquid hydrogen and liquid oxygen" },
          { _id: "Q101-4-C", text: "Kerosene and liquid oxygen" },
          { _id: "Q101-4-D", text: "Hydrazine monopropellant" },
        ],
        correctAnswer: "Q101-4-B",
        possibleAnswers: [],
      },
    ],
  },
  {
    _id: "Q102",
    course: "RS101",
    title: "Rocket Propulsion – Advanced Topics",
    description: "A harder quiz covering advanced propulsion theory.",
    quizType: "GRADED_QUIZ",
    assignmentGroup: "EXAMS",
    shuffleAnswers: false,
    timeLimit: 30,
    timeLimitEnabled: true,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "after_due_date",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2025-07-01",
    availableDate: "2025-06-20",
    untilDate: "2025-07-05",
    published: false,
    questions: [
      {
        _id: "Q102-1",
        type: "TRUE_FALSE",
        title: "Tsiolkovsky Equation",
        question: "The Tsiolkovsky rocket equation relates a rocket's mass ratio to its final velocity using the exhaust velocity.",
        points: 10,
        choices: [],
        correctAnswer: "true",
        possibleAnswers: [],
      },
      {
        _id: "Q102-2",
        type: "MULTIPLE_CHOICE",
        title: "Combustion Chamber Pressure",
        question: "Increasing the combustion chamber pressure in a rocket engine generally results in:",
        points: 15,
        choices: [
          { _id: "Q102-2-A", text: "Decreased thrust and efficiency" },
          { _id: "Q102-2-B", text: "Increased specific impulse and thrust" },
          { _id: "Q102-2-C", text: "No change in performance" },
          { _id: "Q102-2-D", text: "Increased fuel consumption only" },
        ],
        correctAnswer: "Q102-2-B",
        possibleAnswers: [],
      },
    ],
  },
  {
    _id: "Q103",
    course: "RS102",
    title: "Aerodynamics Basics",
    description: "Fundamental concepts in aerodynamics.",
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 15,
    timeLimitEnabled: true,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: "immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2025-06-10",
    availableDate: "2025-05-01",
    untilDate: "2025-06-15",
    published: true,
    questions: [
      {
        _id: "Q103-1",
        type: "MULTIPLE_CHOICE",
        title: "Bernoulli's Principle",
        question: "According to Bernoulli's principle, as the speed of a fluid increases, its pressure:",
        points: 10,
        choices: [
          { _id: "Q103-1-A", text: "Increases" },
          { _id: "Q103-1-B", text: "Decreases" },
          { _id: "Q103-1-C", text: "Stays the same" },
          { _id: "Q103-1-D", text: "First increases then decreases" },
        ],
        correctAnswer: "Q103-1-B",
        possibleAnswers: [],
      },
      {
        _id: "Q103-2",
        type: "TRUE_FALSE",
        title: "Lift Direction",
        question: "Aerodynamic lift always acts perpendicular to the direction of airflow.",
        points: 5,
        choices: [],
        correctAnswer: "true",
        possibleAnswers: [],
      },
      {
        _id: "Q103-3",
        type: "FILL_IN_BLANK",
        title: "Drag Force",
        question: "The aerodynamic force that opposes an aircraft's motion through the air is called _______.",
        points: 5,
        choices: [],
        correctAnswer: "",
        possibleAnswers: ["drag", "aerodynamic drag", "air resistance"],
      },
    ],
  },
  {
    _id: "Q104",
    course: "RS104",
    title: "Organic Chemistry – Functional Groups",
    description: "Test your knowledge of common organic functional groups.",
    quizType: "PRACTICE_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 20,
    timeLimitEnabled: false,
    multipleAttempts: true,
    howManyAttempts: 5,
    showCorrectAnswers: "immediately",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2025-06-30",
    availableDate: "2025-05-01",
    untilDate: "2025-07-01",
    published: true,
    questions: [
      {
        _id: "Q104-1",
        type: "MULTIPLE_CHOICE",
        title: "Alcohol Group",
        question: "Which functional group is present in alcohols?",
        points: 5,
        choices: [
          { _id: "Q104-1-A", text: "-COOH (carboxyl)" },
          { _id: "Q104-1-B", text: "-OH (hydroxyl)" },
          { _id: "Q104-1-C", text: "-NH2 (amino)" },
          { _id: "Q104-1-D", text: "-CHO (aldehyde)" },
        ],
        correctAnswer: "Q104-1-B",
        possibleAnswers: [],
      },
      {
        _id: "Q104-2",
        type: "TRUE_FALSE",
        title: "Isomers",
        question: "Structural isomers have the same molecular formula but different arrangements of atoms.",
        points: 5,
        choices: [],
        correctAnswer: "true",
        possibleAnswers: [],
      },
      {
        _id: "Q104-3",
        type: "FILL_IN_BLANK",
        title: "Benzene Ring",
        question: "The simplest aromatic hydrocarbon with the formula C6H6 is called _______.",
        points: 5,
        choices: [],
        correctAnswer: "",
        possibleAnswers: ["benzene"],
      },
      {
        _id: "Q104-4",
        type: "MULTIPLE_CHOICE",
        title: "Ester Formation",
        question: "An ester is formed from the reaction between:",
        points: 5,
        choices: [
          { _id: "Q104-4-A", text: "An alcohol and an aldehyde" },
          { _id: "Q104-4-B", text: "An alcohol and a carboxylic acid" },
          { _id: "Q104-4-C", text: "A ketone and an amine" },
          { _id: "Q104-4-D", text: "An alkane and an acid" },
        ],
        correctAnswer: "Q104-4-B",
        possibleAnswers: [],
      },
    ],
  },
];
